### ISSUE TITLE
Name Collision

### ISSUE THREAD

**Issue by talbenbasat** [esbenp/react-native-clean-form#27]
Hi,

Looks like a great package but i cant use it due to a collision.
It might be connected to #6 or #8 but it appears to be in a different location

This is the error im getting 
```
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: project/node_modules/react-native/package.json collides with project/node_modules/react-native-clean-form/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: project/node_modules/react-native/packager/package.json collides with project/node_modules/react-native-clean-form/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: project/node_modules/react-native/packager/package.json collides with project/node_modules/react-native-clean-form/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (project/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (project/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

**Comment by markusguenther** [comment]
Hmm I had this with the vector-icons and fixed this for me and the example app. Did you use npm install or yarn install. Because I also had an issue with yarn when I install the package.

Would be nice if you can provide more information :)

**Comment by markusguenther** [comment]
@talbenbasat Do you can provide more information on that issue?

**Comment by talbenbasat** [comment]
Hi,

I'm closing the issue it was my mistake
Thanks for the help :)

**Comment by markusguenther** [comment]
Your welcome :)

**Comment by MattyK14** [comment]
@talbenbasat what was the problem?

**Comment by talbenbasat** [comment]
@MattyK14 Don't remember.
I think i've changed to the latest version and it worked

**Comment by markusguenther** [comment]
@MattyK14 I guess it happens because the npm package was not updated and here we had fixed the issues already.
